// The catalogue's 58 sample titles. One seed becomes two listings — a
// printed edition and an e-book — the way one manuscript does in the
// real data model.

import { baseProductFields, type DisplayProduct } from "./shared";

interface BookSeed {
  id: string;
  slug: string;
  title: string;
  author: string;
  genre: string;
  description: string;
  physicalPriceCents: number;
  ebookPriceCents: number;
  rating: number;
  reviewCount: number;
  stockQty: number;
  isbn: string;
  pages: number;
  coverFrom: string;
  coverTo: string;
}

const BOOK_SEEDS: BookSeed[] = [
  {
    id: "book-1",
    slug: "the-salt-road",
    title: "The Salt Road",
    author: "Mira Voss",
    genre: "Literary Fiction",
    description:
      "A sweeping literary novel following three generations of a coastal family bound together — and torn apart — by the sea they call home.",
    physicalPriceCents: 249900,
    ebookPriceCents: 99900,
    rating: 4.8,
    reviewCount: 128,
    stockQty: 34,
    isbn: "978-1-9821-0341-2",
    pages: 342,
    coverFrom: "#1b2a4a",
    coverTo: "#2e74b5",
  },
  {
    id: "book-2",
    slug: "ledger-of-ash",
    title: "Ledger of Ash",
    author: "D. K. Renshaw",
    genre: "Fantasy",
    description:
      "When a bookkeeper discovers her ledgers can rewrite reality, she must decide what the world owes her — and what she owes it.",
    physicalPriceCents: 279900,
    ebookPriceCents: 119900,
    rating: 4.2,
    reviewCount: 87,
    stockQty: 21,
    isbn: "978-1-9821-0342-9",
    pages: 410,
    coverFrom: "#c9973b",
    coverTo: "#8a641f",
  },
  {
    id: "book-3",
    slug: "signal-loss",
    title: "Signal Loss",
    author: "Priya Anand",
    genre: "Sci-Fi",
    description:
      "A deep-space communications officer receives a message from a ship that was decommissioned twenty years ago.",
    physicalPriceCents: 229900,
    ebookPriceCents: 89900,
    rating: 4.3,
    reviewCount: 63,
    stockQty: 40,
    isbn: "978-1-9821-0343-6",
    pages: 298,
    coverFrom: "#34495e",
    coverTo: "#1b2a4a",
  },
  {
    id: "book-4",
    slug: "quiet-hours",
    title: "Quiet Hours",
    author: "Mira Voss",
    genre: "Poetry",
    description: "A collection of poems on solitude, work, and the small hours of the morning.",
    physicalPriceCents: 169900,
    ebookPriceCents: 69900,
    rating: 4.9,
    reviewCount: 41,
    stockQty: 18,
    isbn: "978-1-9821-0344-3",
    pages: 112,
    coverFrom: "#8e4a7c",
    coverTo: "#4a2a52",
  },
  {
    id: "book-5",
    slug: "the-cartographers-debt",
    title: "The Cartographer's Debt",
    author: "Owen Falk",
    genre: "Historical Fiction",
    description: "An 18th-century mapmaker is commissioned to chart territory that, by treaty, should not exist.",
    physicalPriceCents: 259900,
    ebookPriceCents: 109900,
    rating: 4.4,
    reviewCount: 55,
    stockQty: 12,
    isbn: "978-1-9821-0345-0",
    pages: 388,
    coverFrom: "#b3543f",
    coverTo: "#7a3626",
  },
  {
    id: "book-6",
    slug: "root-and-static",
    title: "Root & Static",
    author: "D. K. Renshaw",
    genre: "Fantasy",
    description:
      "In a city where trees broadcast memories, a young technician is hired to silence one particular grove.",
    physicalPriceCents: 269900,
    ebookPriceCents: 114900,
    rating: 4.7,
    reviewCount: 96,
    stockQty: 27,
    isbn: "978-1-9821-0346-7",
    pages: 356,
    coverFrom: "#4a7c59",
    coverTo: "#2c4a35",
  },
  {
    id: "book-7",
    slug: "low-tide-economics",
    title: "Low Tide Economics",
    author: "Priya Anand",
    genre: "Non-Fiction",
    description:
      "A field guide to the informal markets that keep coastal towns running when the formal ones fail.",
    physicalPriceCents: 299900,
    ebookPriceCents: 139900,
    rating: 4.0,
    reviewCount: 32,
    stockQty: 0,
    isbn: "978-1-9821-0347-4",
    pages: 264,
    coverFrom: "#3f6bb3",
    coverTo: "#254b85",
  },
  {
    id: "book-8",
    slug: "the-understudys-almanac",
    title: "The Understudy's Almanac",
    author: "Owen Falk",
    genre: "Literary Fiction",
    description: "A theater understudy keeps a diary of every role she never got to play — until one night, she does.",
    physicalPriceCents: 239900,
    ebookPriceCents: 94900,
    rating: 3.3,
    reviewCount: 19,
    stockQty: 8,
    isbn: "978-1-9821-0348-1",
    pages: 276,
    coverFrom: "#7a8c3f",
    coverTo: "#4d5a26",
  },
  {
    id: "book-9",
    slug: "emberwright",
    title: "Emberwright",
    author: "William Hernandez",
    genre: "Fantasy",
    description: "A hilarious comedy that will make you laugh out loud.",
    physicalPriceCents: 252508,
    ebookPriceCents: 96979,
    rating: 4.4,
    reviewCount: 199,
    stockQty: 33,
    isbn: "978-1-9821-4436-0",
    pages: 544,
    coverFrom: "#1b2a4a",
    coverTo: "#4a7c59",
  },
  {
    id: "book-10",
    slug: "the-quiet-handoff",
    title: "The Quiet Handoff",
    author: "Aria Gonzalez",
    genre: "Thriller",
    description: "A poignant tale of love and loss.",
    physicalPriceCents: 155444,
    ebookPriceCents: 116368,
    rating: 4.1,
    reviewCount: 28,
    stockQty: 75,
    isbn: "978-1-9821-8118-2",
    pages: 284,
    coverFrom: "#4a7c59",
    coverTo: "#b3543f",
  },
  {
    id: "book-11",
    slug: "whispers-of-the-void",
    title: "Whispers of the Void",
    author: "Maya Martinez",
    genre: "Poetry",
    description: "A poignant tale of love and loss.",
    physicalPriceCents: 317983,
    ebookPriceCents: 102127,
    rating: 4.1,
    reviewCount: 130,
    stockQty: 48,
    isbn: "978-1-9821-2007-4",
    pages: 403,
    coverFrom: "#b3543f",
    coverTo: "#b3543f",
  },
  {
    id: "book-12",
    slug: "the-bands-of-mourning",
    title: "The Bands of Mourning",
    author: "Michael Williams",
    genre: "Non-Fiction",
    description: "A mind-bending science fiction masterpiece.",
    physicalPriceCents: 247604,
    ebookPriceCents: 118045,
    rating: 5,
    reviewCount: 419,
    stockQty: 86,
    isbn: "978-1-9821-3835-5",
    pages: 555,
    coverFrom: "#254b85",
    coverTo: "#254b85",
  },
  {
    id: "book-13",
    slug: "the-obsidian-mirror",
    title: "The Obsidian Mirror",
    author: "Maya Miller",
    genre: "Non-Fiction",
    description: "A gripping story of survival against all odds.",
    physicalPriceCents: 152046,
    ebookPriceCents: 80768,
    rating: 3,
    reviewCount: 347,
    stockQty: 40,
    isbn: "978-1-9821-1863-6",
    pages: 496,
    coverFrom: "#3f6bb3",
    coverTo: "#b3543f",
  },
  {
    id: "book-14",
    slug: "the-lost-metal",
    title: "The Lost Metal",
    author: "Elena Lopez",
    genre: "Sci-Fi",
    description: "A gripping story of survival against all odds.",
    physicalPriceCents: 253795,
    ebookPriceCents: 65691,
    rating: 4,
    reviewCount: 450,
    stockQty: 66,
    isbn: "978-1-9821-2990-8",
    pages: 602,
    coverFrom: "#7a8c3f",
    coverTo: "#2c4a35",
  },
  {
    id: "book-15",
    slug: "heretics-of-dune",
    title: "Heretics of Dune",
    author: "Lisa Hernandez",
    genre: "Mystery",
    description: "A fast-paced action novel with non-stop excitement.",
    physicalPriceCents: 239450,
    ebookPriceCents: 131602,
    rating: 5,
    reviewCount: 124,
    stockQty: 87,
    isbn: "978-1-9821-5099-8",
    pages: 543,
    coverFrom: "#2e74b5",
    coverTo: "#1b2a4a",
  },
  {
    id: "book-16",
    slug: "second-foundation",
    title: "Second Foundation",
    author: "William Garcia",
    genre: "Fantasy",
    description: "A magical fantasy world filled with wonder and danger.",
    physicalPriceCents: 185170,
    ebookPriceCents: 136382,
    rating: 5,
    reviewCount: 319,
    stockQty: 4,
    isbn: "978-1-9821-5290-9",
    pages: 754,
    coverFrom: "#34495e",
    coverTo: "#7a3626",
  },
  {
    id: "book-17",
    slug: "nightfall",
    title: "Nightfall",
    author: "John Chen",
    genre: "Thriller",
    description: "A deep dive into the human psyche.",
    physicalPriceCents: 347711,
    ebookPriceCents: 109544,
    rating: 4,
    reviewCount: 143,
    stockQty: 90,
    isbn: "978-1-9821-5581-9",
    pages: 643,
    coverFrom: "#34495e",
    coverTo: "#b3543f",
  },
  {
    id: "book-18",
    slug: "foundation-and-empire",
    title: "Foundation and Empire",
    author: "Robert Garcia",
    genre: "Literary Fiction",
    description: "A collection of poems that will touch your heart.",
    physicalPriceCents: 199115,
    ebookPriceCents: 138578,
    rating: 3,
    reviewCount: 278,
    stockQty: 92,
    isbn: "978-1-9821-7177-2",
    pages: 135,
    coverFrom: "#7a8c3f",
    coverTo: "#b3543f",
  },
  {
    id: "book-19",
    slug: "foundations-edge",
    title: "Foundations Edge",
    author: "David Smith",
    genre: "Literary Fiction",
    description: "A historical account of a forgotten era.",
    physicalPriceCents: 293432,
    ebookPriceCents: 74376,
    rating: 5,
    reviewCount: 494,
    stockQty: 80,
    isbn: "978-1-9821-7370-0",
    pages: 149,
    coverFrom: "#4a2a52",
    coverTo: "#254b85",
  },
  {
    id: "book-20",
    slug: "the-caves-of-steel",
    title: "The Caves of Steel",
    author: "Sarah Lopez",
    genre: "Thriller",
    description: "A thrilling adventure through time and space.",
    physicalPriceCents: 239794,
    ebookPriceCents: 118686,
    rating: 3,
    reviewCount: 314,
    stockQty: 39,
    isbn: "978-1-9821-7336-9",
    pages: 184,
    coverFrom: "#34495e",
    coverTo: "#8a641f",
  },
  {
    id: "book-21",
    slug: "chapterhouse-dune",
    title: "Chapterhouse Dune",
    author: "Sarah Jones",
    genre: "Romance",
    description: "A mystery that will keep you guessing until the very end.",
    physicalPriceCents: 241367,
    ebookPriceCents: 131019,
    rating: 4,
    reviewCount: 331,
    stockQty: 83,
    isbn: "978-1-9821-4254-6",
    pages: 771,
    coverFrom: "#3f6bb3",
    coverTo: "#2e74b5",
  },
  {
    id: "book-22",
    slug: "song-of-the-sea",
    title: "Song of the Sea",
    author: "James Hernandez",
    genre: "Poetry",
    description: "A thought-provoking look at the future of humanity.",
    physicalPriceCents: 273548,
    ebookPriceCents: 91902,
    rating: 4,
    reviewCount: 299,
    stockQty: 20,
    isbn: "978-1-9821-6711-3",
    pages: 757,
    coverFrom: "#b3543f",
    coverTo: "#34495e",
  },
  {
    id: "book-23",
    slug: "words-of-radiance",
    title: "Words of Radiance",
    author: "Sarah Brown",
    genre: "Fantasy",
    description: "A slow-burn romance that will make you swoon.",
    physicalPriceCents: 172263,
    ebookPriceCents: 87153,
    rating: 3,
    reviewCount: 315,
    stockQty: 40,
    isbn: "978-1-9821-7397-5",
    pages: 130,
    coverFrom: "#b3543f",
    coverTo: "#b3543f",
  },
  {
    id: "book-24",
    slug: "river-of-dreams",
    title: "River of Dreams",
    author: "William Garcia",
    genre: "Literary Fiction",
    description: "A chilling thriller that will keep you up at night.",
    physicalPriceCents: 247444,
    ebookPriceCents: 141734,
    rating: 3,
    reviewCount: 152,
    stockQty: 14,
    isbn: "978-1-9821-2368-5",
    pages: 621,
    coverFrom: "#2e74b5",
    coverTo: "#254b85",
  },
  {
    id: "book-25",
    slug: "echoes-of-the-past",
    title: "Echoes of the Past",
    author: "Aria Jones",
    genre: "Poetry",
    description: "A meticulously researched historical fiction.",
    physicalPriceCents: 244267,
    ebookPriceCents: 111445,
    rating: 4,
    reviewCount: 211,
    stockQty: 95,
    isbn: "978-1-9821-6936-9",
    pages: 179,
    coverFrom: "#2e74b5",
    coverTo: "#4a2a52",
  },
  {
    id: "book-26",
    slug: "forward-the-foundation",
    title: "Forward the Foundation",
    author: "Maya Smith",
    genre: "Historical Fiction",
    description: "A historical account of a forgotten era.",
    physicalPriceCents: 323935,
    ebookPriceCents: 136035,
    rating: 5,
    reviewCount: 477,
    stockQty: 50,
    isbn: "978-1-9821-1569-1",
    pages: 622,
    coverFrom: "#1b2a4a",
    coverTo: "#7a8c3f",
  },
  {
    id: "book-27",
    slug: "the-hero-of-ages",
    title: "The Hero of Ages",
    author: "William Lopez",
    genre: "Historical Fiction",
    description: "A touching drama that will bring tears to your eyes.",
    physicalPriceCents: 249698,
    ebookPriceCents: 142506,
    rating: 4,
    reviewCount: 168,
    stockQty: 9,
    isbn: "978-1-9821-6144-7",
    pages: 697,
    coverFrom: "#3f6bb3",
    coverTo: "#34495e",
  },
  {
    id: "book-28",
    slug: "chronicles-of-ash",
    title: "Chronicles of Ash",
    author: "Marcus Miller",
    genre: "Non-Fiction",
    description: "A thought-provoking look at the future of humanity.",
    physicalPriceCents: 278711,
    ebookPriceCents: 103521,
    rating: 4,
    reviewCount: 93,
    stockQty: 35,
    isbn: "978-1-9821-7901-0",
    pages: 165,
    coverFrom: "#2c4a35",
    coverTo: "#34495e",
  },
  {
    id: "book-29",
    slug: "a-dream-of-spring",
    title: "A Dream of Spring",
    author: "Sarah Miller",
    genre: "Romance",
    description: "A deep dive into the human psyche.",
    physicalPriceCents: 239820,
    ebookPriceCents: 55884,
    rating: 5,
    reviewCount: 86,
    stockQty: 91,
    isbn: "978-1-9821-6862-7",
    pages: 672,
    coverFrom: "#7a8c3f",
    coverTo: "#3f6bb3",
  },
  {
    id: "book-30",
    slug: "the-winds-of-winter",
    title: "The Winds of Winter",
    author: "Lisa Jones",
    genre: "Thriller",
    description: "A terrifying horror story that will haunt your dreams.",
    physicalPriceCents: 303479,
    ebookPriceCents: 60488,
    rating: 4,
    reviewCount: 313,
    stockQty: 66,
    isbn: "978-1-9821-7930-1",
    pages: 460,
    coverFrom: "#7a8c3f",
    coverTo: "#2e74b5",
  },
  {
    id: "book-31",
    slug: "oathbringer",
    title: "Oathbringer",
    author: "David Smith",
    genre: "Fantasy",
    description: "A heartwarming story of friendship and loyalty.",
    physicalPriceCents: 239172,
    ebookPriceCents: 126428,
    rating: 3,
    reviewCount: 449,
    stockQty: 43,
    isbn: "978-1-9821-7324-0",
    pages: 318,
    coverFrom: "#2c4a35",
    coverTo: "#2e74b5",
  },
  {
    id: "book-32",
    slug: "city-of-brass",
    title: "City of Brass",
    author: "Michael Davis",
    genre: "Historical Fiction",
    description: "A terrifying horror story that will haunt your dreams.",
    physicalPriceCents: 155241,
    ebookPriceCents: 73669,
    rating: 3,
    reviewCount: 446,
    stockQty: 60,
    isbn: "978-1-9821-3513-3",
    pages: 275,
    coverFrom: "#1b2a4a",
    coverTo: "#1b2a4a",
  },
  {
    id: "book-33",
    slug: "the-glass-tower",
    title: "The Glass Tower",
    author: "Emma Smith",
    genre: "Thriller",
    description: "A terrifying horror story that will haunt your dreams.",
    physicalPriceCents: 313590,
    ebookPriceCents: 51246,
    rating: 5,
    reviewCount: 407,
    stockQty: 16,
    isbn: "978-1-9821-5700-5",
    pages: 267,
    coverFrom: "#254b85",
    coverTo: "#8a641f",
  },
  {
    id: "book-34",
    slug: "the-emperors-soul",
    title: "The Emperors Soul",
    author: "James Gonzalez",
    genre: "Fantasy",
    description: "A beautiful exploration of identity and belonging.",
    physicalPriceCents: 184769,
    ebookPriceCents: 61475,
    rating: 4,
    reviewCount: 239,
    stockQty: 54,
    isbn: "978-1-9821-1112-3",
    pages: 693,
    coverFrom: "#c9973b",
    coverTo: "#2e74b5",
  },
  {
    id: "book-35",
    slug: "shadows-in-the-light",
    title: "Shadows in the Light",
    author: "David Miller",
    genre: "Sci-Fi",
    description: "A collection of poems that will touch your heart.",
    physicalPriceCents: 196715,
    ebookPriceCents: 86255,
    rating: 3,
    reviewCount: 403,
    stockQty: 59,
    isbn: "978-1-9821-6991-4",
    pages: 718,
    coverFrom: "#8e4a7c",
    coverTo: "#8e4a7c",
  },
  {
    id: "book-36",
    slug: "the-gods-themselves",
    title: "The Gods Themselves",
    author: "Lisa Jones",
    genre: "Non-Fiction",
    description: "A hilarious comedy that will make you laugh out loud.",
    physicalPriceCents: 211317,
    ebookPriceCents: 68236,
    rating: 4,
    reviewCount: 230,
    stockQty: 16,
    isbn: "978-1-9821-2522-1",
    pages: 124,
    coverFrom: "#7a8c3f",
    coverTo: "#8a641f",
  },
  {
    id: "book-37",
    slug: "dune-messiah",
    title: "Dune Messiah",
    author: "Elena Johnson",
    genre: "Mystery",
    description: "A thought-provoking look at the future of humanity.",
    physicalPriceCents: 225419,
    ebookPriceCents: 68091,
    rating: 4,
    reviewCount: 315,
    stockQty: 46,
    isbn: "978-1-9821-7131-8",
    pages: 768,
    coverFrom: "#2c4a35",
    coverTo: "#34495e",
  },
  {
    id: "book-38",
    slug: "god-emperor-of-dune",
    title: "God Emperor of Dune",
    author: "Robert Hernandez",
    genre: "Sci-Fi",
    description: "A collection of poems that will touch your heart.",
    physicalPriceCents: 291570,
    ebookPriceCents: 54156,
    rating: 5,
    reviewCount: 229,
    stockQty: 16,
    isbn: "978-1-9821-1936-0",
    pages: 387,
    coverFrom: "#34495e",
    coverTo: "#4d5a26",
  },
  {
    id: "book-39",
    slug: "the-alloy-of-law",
    title: "The Alloy of Law",
    author: "Robert Brown",
    genre: "Sci-Fi",
    description: "A hilarious comedy that will make you laugh out loud.",
    physicalPriceCents: 287446,
    ebookPriceCents: 130375,
    rating: 5,
    reviewCount: 331,
    stockQty: 89,
    isbn: "978-1-9821-9176-8",
    pages: 297,
    coverFrom: "#3f6bb3",
    coverTo: "#2e74b5",
  },
  {
    id: "book-40",
    slug: "foundation",
    title: "Foundation",
    author: "Robert Hernandez",
    genre: "Fantasy",
    description: "A thought-provoking look at the future of humanity.",
    physicalPriceCents: 250977,
    ebookPriceCents: 132734,
    rating: 3,
    reviewCount: 42,
    stockQty: 83,
    isbn: "978-1-9821-9455-1",
    pages: 270,
    coverFrom: "#b3543f",
    coverTo: "#4d5a26",
  },
  {
    id: "book-41",
    slug: "the-end-of-eternity",
    title: "The End of Eternity",
    author: "Marcus Lopez",
    genre: "Thriller",
    description: "A hilarious comedy that will make you laugh out loud.",
    physicalPriceCents: 267666,
    ebookPriceCents: 51928,
    rating: 4,
    reviewCount: 311,
    stockQty: 36,
    isbn: "978-1-9821-4776-6",
    pages: 614,
    coverFrom: "#3f6bb3",
    coverTo: "#2c4a35",
  },
  {
    id: "book-42",
    slug: "a-dance-of-stars",
    title: "A Dance of Stars",
    author: "John Miller",
    genre: "Romance",
    description: "A chilling thriller that will keep you up at night.",
    physicalPriceCents: 211496,
    ebookPriceCents: 143564,
    rating: 5,
    reviewCount: 483,
    stockQty: 9,
    isbn: "978-1-9821-6800-8",
    pages: 718,
    coverFrom: "#4a2a52",
    coverTo: "#c9973b",
  },
  {
    id: "book-43",
    slug: "a-storm-of-swords",
    title: "A Storm of Swords",
    author: "William Brown",
    genre: "Historical Fiction",
    description: "A hilarious comedy that will make you laugh out loud.",
    physicalPriceCents: 330778,
    ebookPriceCents: 143725,
    rating: 5,
    reviewCount: 168,
    stockQty: 55,
    isbn: "978-1-9821-6385-0",
    pages: 721,
    coverFrom: "#2c4a35",
    coverTo: "#2e74b5",
  },
  {
    id: "book-44",
    slug: "dune",
    title: "Dune",
    author: "David Smith",
    genre: "Romance",
    description: "A poignant tale of love and loss.",
    physicalPriceCents: 166268,
    ebookPriceCents: 145711,
    rating: 4,
    reviewCount: 172,
    stockQty: 31,
    isbn: "978-1-9821-4363-9",
    pages: 157,
    coverFrom: "#2c4a35",
    coverTo: "#254b85",
  },
  {
    id: "book-45",
    slug: "the-last-oasis",
    title: "The Last Oasis",
    author: "Michael Davis",
    genre: "Thriller",
    description: "A hilarious comedy that will make you laugh out loud.",
    physicalPriceCents: 274933,
    ebookPriceCents: 134612,
    rating: 4,
    reviewCount: 491,
    stockQty: 39,
    isbn: "978-1-9821-9297-8",
    pages: 476,
    coverFrom: "#c9973b",
    coverTo: "#1b2a4a",
  },
  {
    id: "book-46",
    slug: "shadows-of-self",
    title: "Shadows of Self",
    author: "Lisa Gonzalez",
    genre: "Sci-Fi",
    description: "A slow-burn romance that will make you swoon.",
    physicalPriceCents: 167972,
    ebookPriceCents: 62025,
    rating: 5,
    reviewCount: 366,
    stockQty: 4,
    isbn: "978-1-9821-5182-4",
    pages: 416,
    coverFrom: "#8e4a7c",
    coverTo: "#8e4a7c",
  },
  {
    id: "book-47",
    slug: "the-iron-throne",
    title: "The Iron Throne",
    author: "Nina Jones",
    genre: "Historical Fiction",
    description: "A heartwarming story of friendship and loyalty.",
    physicalPriceCents: 285851,
    ebookPriceCents: 59267,
    rating: 3,
    reviewCount: 41,
    stockQty: 94,
    isbn: "978-1-9821-8650-5",
    pages: 396,
    coverFrom: "#1b2a4a",
    coverTo: "#2c4a35",
  },
  {
    id: "book-48",
    slug: "rhythm-of-war",
    title: "Rhythm of War",
    author: "Robert Miller",
    genre: "Mystery",
    description: "A heartwarming story of friendship and loyalty.",
    physicalPriceCents: 244539,
    ebookPriceCents: 109820,
    rating: 4,
    reviewCount: 284,
    stockQty: 40,
    isbn: "978-1-9821-2608-4",
    pages: 686,
    coverFrom: "#7a3626",
    coverTo: "#2c4a35",
  },
  {
    id: "book-49",
    slug: "wind-from-the-east",
    title: "Wind from the East",
    author: "William Hernandez",
    genre: "Sci-Fi",
    description: "A heartwarming story of friendship and loyalty.",
    physicalPriceCents: 227955,
    ebookPriceCents: 88797,
    rating: 3,
    reviewCount: 202,
    stockQty: 90,
    isbn: "978-1-9821-2074-3",
    pages: 114,
    coverFrom: "#2e74b5",
    coverTo: "#1b2a4a",
  },
  {
    id: "book-50",
    slug: "the-midnight-library",
    title: "The Midnight Library",
    author: "Emma Rodriguez",
    genre: "Historical Fiction",
    description: "A thought-provoking look at the future of humanity.",
    physicalPriceCents: 280487,
    ebookPriceCents: 131819,
    rating: 4,
    reviewCount: 330,
    stockQty: 65,
    isbn: "978-1-9821-2918-7",
    pages: 576,
    coverFrom: "#3f6bb3",
    coverTo: "#8a641f",
  },
  {
    id: "book-51",
    slug: "elantris",
    title: "Elantris",
    author: "Michael Smith",
    genre: "Thriller",
    description: "A terrifying horror story that will haunt your dreams.",
    physicalPriceCents: 232142,
    ebookPriceCents: 89271,
    rating: 5,
    reviewCount: 321,
    stockQty: 86,
    isbn: "978-1-9821-2679-5",
    pages: 184,
    coverFrom: "#34495e",
    coverTo: "#8e4a7c",
  },
  {
    id: "book-52",
    slug: "a-feast-for-crows",
    title: "A Feast for Crows",
    author: "Robert Chen",
    genre: "Thriller",
    description: "A thought-provoking look at the future of humanity.",
    physicalPriceCents: 270743,
    ebookPriceCents: 132489,
    rating: 5,
    reviewCount: 429,
    stockQty: 82,
    isbn: "978-1-9821-4811-8",
    pages: 119,
    coverFrom: "#4a2a52",
    coverTo: "#1b2a4a",
  },
  {
    id: "book-53",
    slug: "a-dance-with-dragons",
    title: "A Dance with Dragons",
    author: "Maya Davis",
    genre: "Fantasy",
    description: "A deep dive into the human psyche.",
    physicalPriceCents: 207321,
    ebookPriceCents: 127298,
    rating: 3,
    reviewCount: 293,
    stockQty: 53,
    isbn: "978-1-9821-3889-1",
    pages: 771,
    coverFrom: "#2c4a35",
    coverTo: "#b3543f",
  },
  {
    id: "book-54",
    slug: "beyond-the-horizon",
    title: "Beyond the Horizon",
    author: "James Johnson",
    genre: "Sci-Fi",
    description: "A touching drama that will bring tears to your eyes.",
    physicalPriceCents: 265492,
    ebookPriceCents: 103009,
    rating: 5,
    reviewCount: 458,
    stockQty: 64,
    isbn: "978-1-9821-4090-9",
    pages: 420,
    coverFrom: "#2c4a35",
    coverTo: "#3f6bb3",
  },
  {
    id: "book-55",
    slug: "children-of-dune",
    title: "Children of Dune",
    author: "James Lopez",
    genre: "Romance",
    description: "A historical account of a forgotten era.",
    physicalPriceCents: 207805,
    ebookPriceCents: 146296,
    rating: 3,
    reviewCount: 102,
    stockQty: 65,
    isbn: "978-1-9821-6033-0",
    pages: 279,
    coverFrom: "#254b85",
    coverTo: "#34495e",
  },
  {
    id: "book-56",
    slug: "a-clash-of-kings",
    title: "A Clash of Kings",
    author: "Emma Hernandez",
    genre: "Mystery",
    description: "A terrifying horror story that will haunt your dreams.",
    physicalPriceCents: 321255,
    ebookPriceCents: 86996,
    rating: 4,
    reviewCount: 24,
    stockQty: 3,
    isbn: "978-1-9821-4129-1",
    pages: 173,
    coverFrom: "#254b85",
    coverTo: "#254b85",
  },
  {
    id: "book-57",
    slug: "nemesis",
    title: "Nemesis",
    author: "Lisa Miller",
    genre: "Romance",
    description: "A collection of poems that will touch your heart.",
    physicalPriceCents: 162995,
    ebookPriceCents: 67998,
    rating: 4,
    reviewCount: 300,
    stockQty: 37,
    isbn: "978-1-9821-1420-8",
    pages: 175,
    coverFrom: "#254b85",
    coverTo: "#7a3626",
  },
  {
    id: "book-58",
    slug: "the-silent-echo",
    title: "The Silent Echo",
    author: "Lisa Miller",
    genre: "Romance",
    description: "A hilarious comedy that will make you laugh out loud.",
    physicalPriceCents: 163419,
    ebookPriceCents: 76660,
    rating: 4,
    reviewCount: 468,
    stockQty: 15,
    isbn: "978-1-9821-1738-6",
    pages: 790,
    coverFrom: "#8e4a7c",
    coverTo: "#1b2a4a",
  },
];

export const SAMPLE_BOOKS: DisplayProduct[] = BOOK_SEEDS.map((b) => ({
  ...baseProductFields(),
  id: `${b.id}-physical`,
  type: "PHYSICAL_BOOK",
  title: b.title,
  author: b.author,
  slug: b.slug,
  description: `${b.description}\n\n${b.pages} pages.`,
  priceCents: b.physicalPriceCents,
  coverImageUrl: null,
  stockQty: b.stockQty,
  isbn: b.isbn,
  weightGrams: 320,
  formats: [],
  sampleUrl: null,
  turnaroundDays: null,
  pages: b.pages,
  genre: b.genre,
  rating: b.rating,
  reviewCount: b.reviewCount,
  coverFrom: b.coverFrom,
  coverTo: b.coverTo,
})) as DisplayProduct[];

export const SAMPLE_EBOOKS: DisplayProduct[] = BOOK_SEEDS.map((b) => ({
  ...baseProductFields(),
  id: `${b.id}-ebook`,
  type: "EBOOK",
  title: b.title,
  author: b.author,
  slug: `${b.slug}-ebook`,
  description: b.description,
  priceCents: b.ebookPriceCents,
  coverImageUrl: null,
  stockQty: null,
  isbn: null,
  formats: ["EPUB", "MOBI", "PDF"],
  sampleUrl: null,
  turnaroundDays: null,
  pages: b.pages,
  genre: b.genre,
  rating: b.rating,
  reviewCount: Math.round(b.reviewCount * 0.6),
  coverFrom: b.coverFrom,
  coverTo: b.coverTo,
})) as DisplayProduct[];
