#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# This wizard configures apps/admin's own auth project, so it writes to that
# app's local env file, not the repo-root .env.
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
ENV_FILE="apps/admin/.env.local"
SQL_FILE="packages/database/prisma/sql/sync_staff.sql"

banner "apps/admin — dedicated auth Supabase project"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Create the project"
say "apps/admin authenticates against its OWN Supabase project so that a staff"
say "identity can never be created by the storefront's public signup form."
say "This is a NEW project, separate from the storefront one."
open_url "https://supabase.com/dashboard/new"
step "Name it something like 'digital-storefront-admin'."
step "Set a strong database password (save it in your password manager — you"
step "  will not need it for apps/admin, which never touches this project's DB)."
step "Pick the same region as the storefront project."
step "Create, and wait for provisioning to finish (~2 min)."
pause "Project shows as active?"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Copy the API credentials"
say "From this project's API settings, copy three values."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Project URL  →  paste below."
ask NEXT_PUBLIC_AUTH_SUPABASE_URL "Project URL (https://xxxx.supabase.co):"
step "Project API keys → 'anon' / 'publishable' key  →  paste below."
ask NEXT_PUBLIC_AUTH_SUPABASE_PUBLISHABLE_KEY "anon / publishable key:"
step "Project API keys → reveal the 'service_role' key  →  paste below."
warn "service_role bypasses Row-Level Security. It is server-only and is"
warn "written to apps/admin/.env.local (git-ignored). Never expose it to a browser."
ask_secret AUTH_SUPABASE_SERVICE_ROLE_KEY "service_role key:"
write_env NEXT_PUBLIC_AUTH_SUPABASE_URL "$NEXT_PUBLIC_AUTH_SUPABASE_URL"
write_env NEXT_PUBLIC_AUTH_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_AUTH_SUPABASE_PUBLISHABLE_KEY"
write_env AUTH_SUPABASE_SERVICE_ROLE_KEY "$AUTH_SUPABASE_SERVICE_ROLE_KEY"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Create the staff users table"
say "This project has no Prisma-managed schema. Run $SQL_FILE in its SQL"
say "editor: it creates public.users, the auth.users -> public.users sync"
say "trigger, and a self-read RLS policy."
open_url "https://supabase.com/dashboard/project/_/sql/new"
if [[ -f "$SQL_FILE" ]]; then
  step "Copy the SQL below (also at $SQL_FILE), paste into the editor, Run."
  printf '\n%s────────────────────────────────────────────────────────%s\n' "$DIM" "$RESET"
  cat "$SQL_FILE"
  printf '%s────────────────────────────────────────────────────────%s\n\n' "$DIM" "$RESET"
else
  warn "Couldn't find $SQL_FILE — run this wizard from the repo checkout."
  step "Open packages/database/prisma/sql/sync_staff.sql, paste it in, Run."
fi
pause "SQL ran with no errors?"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Lock down sign-ups"
say "No one may self-register in this project — staff accounts are created by"
say "the Owner only."
open_url "https://supabase.com/dashboard/project/_/auth/providers"
step "Email provider: turn OFF 'Allow new users to sign up' (the label may"
step "  read 'Enable sign-ups' / live under Authentication → Sign In / Providers"
step "  depending on dashboard version). Keep 'Confirm email' as you prefer."
step "Google (and any other OAuth) provider: DISABLE it, unless you have a"
step "  specific staff-only workspace to restrict it to. A consumer Google"
step "  login here would reopen the exact hole we're closing."
pause "Sign-ups disabled and OAuth reviewed?"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Create the Owner account"
say "Add the Publisher's account by hand — this is the only account that will"
say "exist at first."
open_url "https://supabase.com/dashboard/project/_/auth/users"
step "Add user → 'Create new user'. Enter the Owner's email + a strong"
step "  temporary password. Tick 'Auto Confirm User'."
ask OWNER_EMAIL "Owner email you just entered:"
pause "User created and listed?"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Promote the Owner"
say "The sync trigger created their public.users row as READER. Raise it to"
say "OWNER so they can pass the ADMIN_ROLES gate."
open_url "https://supabase.com/dashboard/project/_/sql/new"
step "Run this in the SQL editor:"
printf '\n'
if [[ -n "${OWNER_EMAIL:-}" ]]; then
  printf "      %supdate public.users set role = 'OWNER' where email = '%s';%s\n" "$BOLD" "$OWNER_EMAIL" "$RESET"
else
  printf "      %supdate public.users set role = 'OWNER' where email = 'owner@example.com';%s\n" "$BOLD" "$RESET"
fi
printf '\n'
step "Expect 'Success. 1 row affected.'"
pause "Row updated?"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Deploy config + storefront cleanup"
say "Two things this wizard can't do for you:"
printf '\n'
step "Vercel — on the apps/admin project, set the same three vars"
step "  (NEXT_PUBLIC_AUTH_SUPABASE_URL, NEXT_PUBLIC_AUTH_SUPABASE_PUBLISHABLE_KEY,"
step "  AUTH_SUPABASE_SERVICE_ROLE_KEY) in Settings → Environment Variables,"
step "  then redeploy."
open_url "https://vercel.com/dashboard"
printf '\n'
step "Storefront project — any staff who currently have a role in the"
step "  storefront's public.users no longer get in through it. In the"
step "  STOREFRONT project's SQL editor, demote them:"
printf "\n      %supdate public.users set role = 'READER' where role in ('SUPPORT','EDITOR','OWNER');%s\n\n" "$BOLD" "$RESET"
note "(Their storefront customer account keeps working as a normal READER.)"
pause "Noted — I'll handle Vercel + the storefront demotion."
SKIPPED+=("Vercel: set the 3 NEXT_PUBLIC_AUTH_SUPABASE_* / AUTH_SUPABASE_SERVICE_ROLE_KEY vars on the apps/admin project and redeploy")
SKIPPED+=("Storefront project: demote SUPPORT/EDITOR/OWNER rows in public.users back to READER")

finish
say "Next: restart 'npm run dev:admin', sign in as the Owner against the new"
say "project, and confirm a customer account from the storefront can NOT sign in."
